# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Mainwindow")
        MainWindow.setWindowTitle("Spread_sheet")
        MainWindow.resize(1046, 652)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setStatusTip("")
        self.tabWidget.setObjectName("tabWidget")
        self.FinePlate = QtWidgets.QWidget()
        self.FinePlate.setObjectName("FinePlate")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.FinePlate)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableWidget_FinPlate = QtWidgets.QTableWidget(self.FinePlate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_FinPlate.sizePolicy().hasHeightForWidth())
        self.tableWidget_FinPlate.setSizePolicy(sizePolicy)
        self.tableWidget_FinPlate.setMidLineWidth(0)
        self.tableWidget_FinPlate.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget_FinPlate.setAlternatingRowColors(True)
        self.tableWidget_FinPlate.setRowCount(1000)
        self.tableWidget_FinPlate.setColumnCount(7)
        self.tableWidget_FinPlate.setObjectName("tableWidget_FinPlate")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_FinPlate.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_FinPlate.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_FinPlate.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_FinPlate.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_FinPlate.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_FinPlate.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        item.setFont(font)
        self.tableWidget_FinPlate.setHorizontalHeaderItem(6, item)
        self.tableWidget_FinPlate.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_FinPlate.verticalHeader().setVisible(False)
        self.verticalLayout_4.addWidget(self.tableWidget_FinPlate)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_1 = QtWidgets.QPushButton(self.FinePlate)
        self.pushButton_1.setToolTip("")
        self.pushButton_1.setObjectName("pushButton_1")
        self.horizontalLayout_2.addWidget(self.pushButton_1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButton_2 = QtWidgets.QPushButton(self.FinePlate)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pushButton_3 = QtWidgets.QPushButton(self.FinePlate)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.FinePlate, "")
        self.TensionMember = QtWidgets.QWidget()
        self.TensionMember.setObjectName("TensionMember")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.TensionMember)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tableWidget_TensionMember = QtWidgets.QTableWidget(self.TensionMember)
        self.tableWidget_TensionMember.setAlternatingRowColors(True)
        self.tableWidget_TensionMember.setRowCount(100)
        self.tableWidget_TensionMember.setObjectName("tableWidget_TensionMember")
        self.tableWidget_TensionMember.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_TensionMember.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_TensionMember.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_TensionMember.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignBottom)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_TensionMember.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_TensionMember.setHorizontalHeaderItem(4, item)
        self.tableWidget_TensionMember.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_TensionMember.horizontalHeader().setDefaultSectionSize(200)
        self.tableWidget_TensionMember.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_TensionMember.verticalHeader().setVisible(False)
        self.verticalLayout_6.addWidget(self.tableWidget_TensionMember)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.pushButton_4 = QtWidgets.QPushButton(self.TensionMember)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.pushButton_5 = QtWidgets.QPushButton(self.TensionMember)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_3.addWidget(self.pushButton_5)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.pushButton_6 = QtWidgets.QPushButton(self.TensionMember)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_3.addWidget(self.pushButton_6)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.TensionMember, "")
        self.BCEndPlate = QtWidgets.QWidget()
        self.BCEndPlate.setObjectName("BCEndPlate")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.BCEndPlate)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tableWidget_BCEndPlate = QtWidgets.QTableWidget(self.BCEndPlate)
        self.tableWidget_BCEndPlate.setAlternatingRowColors(True)
        self.tableWidget_BCEndPlate.setRowCount(100)
        self.tableWidget_BCEndPlate.setObjectName("tableWidget_BCEndPlate")
        self.tableWidget_BCEndPlate.setColumnCount(8)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_BCEndPlate.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_BCEndPlate.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_BCEndPlate.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_BCEndPlate.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_BCEndPlate.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_BCEndPlate.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_BCEndPlate.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_BCEndPlate.setHorizontalHeaderItem(7, item)
        self.tableWidget_BCEndPlate.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_BCEndPlate.verticalHeader().setVisible(False)
        self.verticalLayout_7.addWidget(self.tableWidget_BCEndPlate)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.pushButton_7 = QtWidgets.QPushButton(self.BCEndPlate)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_4.addWidget(self.pushButton_7)
        spacerItem9 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.pushButton_8 = QtWidgets.QPushButton(self.BCEndPlate)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_4.addWidget(self.pushButton_8)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        self.pushButton_9 = QtWidgets.QPushButton(self.BCEndPlate)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_4.addWidget(self.pushButton_9)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.BCEndPlate, "")
        self.CleatAngle = QtWidgets.QWidget()
        self.CleatAngle.setObjectName("CleatAngle")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.CleatAngle)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget_CleatAngle = QtWidgets.QTableWidget(self.CleatAngle)
        self.tableWidget_CleatAngle.setAlternatingRowColors(True)
        self.tableWidget_CleatAngle.setRowCount(100)
        self.tableWidget_CleatAngle.setObjectName("tableWidget_CleatAngle")
        self.tableWidget_CleatAngle.setColumnCount(7)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_CleatAngle.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_CleatAngle.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_CleatAngle.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_CleatAngle.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_CleatAngle.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_CleatAngle.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_CleatAngle.setHorizontalHeaderItem(6, item)
        self.tableWidget_CleatAngle.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_CleatAngle.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.tableWidget_CleatAngle)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem12)
        self.pushButton_10 = QtWidgets.QPushButton(self.CleatAngle)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout.addWidget(self.pushButton_10)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem13)
        self.pushButton_11 = QtWidgets.QPushButton(self.CleatAngle)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout.addWidget(self.pushButton_11)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem14)
        self.pushButton_12 = QtWidgets.QPushButton(self.CleatAngle)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout.addWidget(self.pushButton_12)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem15)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.CleatAngle, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.FinePlate.setStatusTip(_translate("MainWindow", "FinPlate_Module"))
        self.tableWidget_FinPlate.setSortingEnabled(False)
        item = self.tableWidget_FinPlate.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_FinPlate.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Connection type"))
        item = self.tableWidget_FinPlate.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Axial load"))
        item = self.tableWidget_FinPlate.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Shear load"))
        item = self.tableWidget_FinPlate.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Bolt diameter"))
        item = self.tableWidget_FinPlate.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Bolt grade"))
        item = self.tableWidget_FinPlate.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Plate thickness"))
        self.pushButton_1.setStatusTip(_translate("MainWindow", "Click to Load csv/xlsx file!!"))
        self.pushButton_1.setText(_translate("MainWindow", "Load"))
        self.pushButton_2.setStatusTip(_translate("MainWindow", "Click to validate the dataframe!!"))
        self.pushButton_2.setText(_translate("MainWindow", "Validate"))
        self.pushButton_3.setStatusTip(_translate("MainWindow", "Click to save as text file!!"))
        self.pushButton_3.setText(_translate("MainWindow", "Submit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.FinePlate), _translate("MainWindow", "FinPlate"))
        self.tableWidget_TensionMember.setStatusTip(_translate("MainWindow", "TensionMember_Module"))
        item = self.tableWidget_TensionMember.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_TensionMember.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Member length"))
        item = self.tableWidget_TensionMember.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Tensile load"))
        item = self.tableWidget_TensionMember.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Support condition at End 1"))
        item = self.tableWidget_TensionMember.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Support condition at End 2"))
        self.pushButton_4.setStatusTip(_translate("MainWindow", "Click to Load csv/xlsx file!!"))
        self.pushButton_4.setText(_translate("MainWindow", "Load"))
        self.pushButton_5.setStatusTip(_translate("MainWindow", "Click to validate the dataframe!!"))
        self.pushButton_5.setText(_translate("MainWindow", "Validate"))
        self.pushButton_6.setStatusTip(_translate("MainWindow", "Click to save as text file!!"))
        self.pushButton_6.setText(_translate("MainWindow", "Submit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TensionMember), _translate("MainWindow", "TensionMember"))
        self.tableWidget_BCEndPlate.setStatusTip(_translate("MainWindow", "BCEndPlate_Module"))
        item = self.tableWidget_BCEndPlate.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_BCEndPlate.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "End plate type"))
        item = self.tableWidget_BCEndPlate.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Shear load"))
        item = self.tableWidget_BCEndPlate.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Axial load"))
        item = self.tableWidget_BCEndPlate.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Moment Load"))
        item = self.tableWidget_BCEndPlate.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Bolt diameter"))
        item = self.tableWidget_BCEndPlate.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Bolt grade"))
        item = self.tableWidget_BCEndPlate.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Plate thickness"))
        self.pushButton_7.setStatusTip(_translate("MainWindow", "Click to Load csv/xlsx file!!"))
        self.pushButton_7.setText(_translate("MainWindow", "Load"))
        self.pushButton_8.setStatusTip(_translate("MainWindow", "Click to validate the dataframe!!"))
        self.pushButton_8.setText(_translate("MainWindow", "Validate"))
        self.pushButton_9.setStatusTip(_translate("MainWindow", "Click to save as text file!!"))
        self.pushButton_9.setText(_translate("MainWindow", "Submit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.BCEndPlate), _translate("MainWindow", "BCEndPlate"))
        self.tableWidget_CleatAngle.setStatusTip(_translate("MainWindow", "CleatAngle_Module"))
        item = self.tableWidget_CleatAngle.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_CleatAngle.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Angle leg 1"))
        item = self.tableWidget_CleatAngle.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Angle leg 2"))
        item = self.tableWidget_CleatAngle.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Angle thickness"))
        item = self.tableWidget_CleatAngle.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Shear load"))
        item = self.tableWidget_CleatAngle.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Bolt diameter"))
        item = self.tableWidget_CleatAngle.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Bolt grade"))
        self.pushButton_10.setStatusTip(_translate("MainWindow", "Click to Load csv/xlsx file!!"))
        self.pushButton_10.setText(_translate("MainWindow", "Load"))
        self.pushButton_11.setStatusTip(_translate("MainWindow", "Click to validate the dataframe!!"))
        self.pushButton_11.setText(_translate("MainWindow", "Validate"))
        self.pushButton_12.setStatusTip(_translate("MainWindow", "Click to save as text file!!"))
        self.pushButton_12.setText(_translate("MainWindow", "Submit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.CleatAngle), _translate("MainWindow", "CleatAngle"))
